apiVersion: v1
kind: persistentVolume
metadata:
  name: pvvol
spec:
  persistentVolumeClaim: Recycle
  capacity:
    storage: 1Gi
    accessModes:
    - ReadWriteMany
  nfs:
    server: 10.128.0.16
    path: /var/nfs/general
    readonly: false

  
