apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: ""  # This forces it to look for your manual PV
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
